version: '3.5'

services:
  telegram-download-daemon-ng:
    #build: .
    image: nyaran/telegram-download-daemon-ng:latest
    container_name: telegram-download
    read_only: true
    environment:
      TELEGRAM_DAEMON_API_ID: "YOUR API ID HERE"
      TELEGRAM_DAEMON_API_HASH: "YOUR API HASH HERE"
      TELEGRAM_DAEMON_CHANNEL: "YOUR CHANNEL ID HERE"
      TELEGRAM_DAEMON_DEST: "/downloads"
      TELEGRAM_DAEMON_SESSION_PATH: "/session"
      TELEGRAM_DAEMON_TEMP: "/temp"
      #TELEGRAM_DAEMON_WORKERS: 2
    volumes:
      - downloads:/downloads
      - sessions:/session
      - temp:/temp
    restart: unless-stopped
volumes:
  downloads:
  sessions:
  temp:
