name: Build
description: Build the project and create artifacts
input:
    python-version:
        description: 'Python version to use'
        required: false
    uv-version:
        description: 'uv version to use'
        required: false
runs:
    using: 'composite'
    steps:
        - name: Setup environment
          uses: ./.github/workflows/actions/set-environment
          with:
              python-version: ${{ inputs.python-version }}
              uv-version: ${{ inputs.uv-version }}

        - name: Install the project
          run: uv sync --locked --all-extras --dev
          shell: bash

        - name: Build binary wheel and source tarball
          run: uv build
          shell: bash

        - name: Upload wheel artifact
          uses: actions/upload-artifact@v4
          with:
              name: dist
              path: dist/*.whl