name: Build
description: Build the project and create artifacts
input:
    python-version:
        description: 'Python version to use'
        required: false
        default: '3.9'
    uv-version:
        description: 'uv version to use'
        required: false
        default: 'latest'
runs:
    using: 'composite'
    steps:
        - name: Set up python
          uses: actions/setup-python@v6
          with:
              python-version: ${{ inputs.python-version }}

        - name: Install uv
          uses: astral-sh/setup-uv@v6
          with:
              uv-version: ${{ inputs.uv-version }}

        - name: Install the project
          run: uv sync --locked --all-extras --dev

        - name: Build binary wheel and source tarball
          run: uv build

        - name: Upload wheel artifact
          uses: actions/upload-artifact@v4
          with:
              name: dist
              path: dist/*.whl