name: Setup Environment
description: Setup the environment
input:
    python-version:
        description: 'Python version to use'
        required: false
        default: '3.9'
    uv-version:
        description: 'uv version to use'
        required: false
        default: 'latest'
runs:
    using: 'composite'
    steps:
        - name: Set up python
          uses: actions/setup-python@v6
          with:
              python-version: ${{ inputs.python-version }}

        - name: Install uv
          uses: astral-sh/setup-uv@v6
          with:
              uv-version: ${{ inputs.uv-version }}
