name: Create GitHub Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if:  startsWith(github.head_ref, 'release/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Build Project
        uses: ./.github/workflows/actions/build-package

      - name: Get version
        id: get-version
        run: echo "version=$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2.3.3
        with:
          draft: true
          tag_name: v${{ steps.get-version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
